name: chamameg

services:
  postgresql:
    image: postgres
    container_name: chamameg-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a6d86202fec026e664a92019ff58cdbeb573f82737ad1601915aa51f047f
      POSTGRES_DB: clean_arch_db
      TZ: "America/Sao_Paulo"
    volumes:
      - chamameg-postgresql-data:/var/lib/postgresql/data
    networks:
      - containers-network

  redis:
    image: redis:latest
    container_name: chamameg-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - chamameg-redis-data:/data
    networks:
      - containers-network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  chamameg-postgresql-data:
  chamameg-redis-data:

networks:
  containers-network:
    driver: bridge
